apiVersion: batch/v1
kind: Job
metadata:
  name: pub
spec:
  template:
    spec:
      containers:
      - name: pub-con
        image: namickey/pub-mqtt:1.0
        imagePullPolicy: Never
        command: ["python", "-u", "pub.py"]
      restartPolicy: Never
  backoffLimit: 1
