version: '3'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./src:/projects"
    tty: true
    environment:
      TZ: Asia/Tokyo
    command: gunicorn -w 2 -b 127.0.0.1:5000 --access-logfile - app:app
