apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-pod
  template:
    metadata:
      labels:
        app: flask-pod
    spec:
      containers:
      - name: flask-container
        image: namickey/flaskpodmix:latest
        command: ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]
        ports:
        - containerPort: 5000
